In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

In [3]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [4]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [5]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [6]:
df_with_dummies = df[["data1"]].join(dummies)

In [7]:
df_with_dummies

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [8]:
mnames = ["movie_id", "title", "genres"]

In [12]:
movies = pd.read_table(r"D:\xiazai\pydata-book-3rd-edition\datasets\movielens\movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

In [13]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [14]:
dummies = movies["genres"].str.get_dummies("|")

In [15]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [17]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [19]:
movies_windic.iloc[1:2]

movie_id           title                        genres  Genre_Action  \
1         2  Jumanji (1995)  Adventure|Children's|Fantasy             0   

   Genre_Adventure  Genre_Animation  Genre_Children's  Genre_Comedy  \
1                1                0                 1             0   

   Genre_Crime  Genre_Documentary  ...  Genre_Fantasy  Genre_Film-Noir  \
1            0                  0  ...              1                0   

   Genre_Horror  Genre_Musical  Genre_Mystery  Genre_Romance  Genre_Sci-Fi  \
1             0              0              0              0             0   

   Genre_Thriller  Genre_War  Genre_Western  
1               0          0              0  

[1 rows x 21 columns]

In [20]:
import numpy as np

In [21]:
np.random.seed(12345)

In [22]:
values = np.random.uniform(size=10)

In [23]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [25]:
pd.get_dummies(pd.cut(values, 5))

(0.183, 0.34]  (0.34, 0.496]  (0.496, 0.652]  (0.652, 0.808]  \
0          False          False           False           False   
1           True          False           False           False   
2           True          False           False           False   
3           True          False           False           False   
4          False          False            True           False   
5          False          False            True           False   
6          False          False           False           False   
7          False          False           False            True   
8          False          False           False            True   
9          False          False           False            True   

   (0.808, 0.965]  
0            True  
1           False  
2           False  
3           False  
4           False  
5           False  
6            True  
7           False  
8           False  
9           False

In [26]:
s = pd.Series([1, 2, 3, None])

In [27]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [28]:
s.dtype

dtype('float64')

In [29]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [30]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [31]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [33]:
s.dtype

Int64Dtype()

In [34]:
s[3]

<NA>

In [35]:
s[3] is pd.NA

True

In [36]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [37]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [38]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [39]:
val = "a,b, guido"

In [40]:
val.split(",")

['a', 'b', ' guido']

In [41]:
pieces = [x.strip() for x in val.split(",")]

In [42]:
first, second, third = pieces

In [43]:
first + "::" + second + "::" + third

'a::b::guido'

In [44]:
"::".join(pieces)

'a::b::guido'

In [45]:
"guido" in val

True

In [46]:
val.index(",")

1

In [47]:
val.find(":")

-1

In [48]:
val.count(",")

2

In [50]:
val.replace(",", "::")

'a::b:: guido'

In [51]:
val.replace(",", "")

'ab guido'

In [52]:
import re

In [53]:
text = "foo    bar\t baz  \tque"

In [54]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'que']

In [55]:
regex = re.compile(r"\s+")

In [56]:
regex.split(text)

['foo', 'bar', 'baz', 'que']

In [57]:
regex.findall(text)

['    ', '\t ', '  \t']

In [58]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [60]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [61]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [63]:
m = regex.search(text)

In [64]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [65]:
text[m.start():m.end()]

'dave@google.com'

In [66]:
print(regex.match(text))

None


In [67]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [68]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [69]:
regex = re.compilg

In [71]:
m = regex.match("wesm@bright.net")

In [72]:
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [73]:
m.groups()

('wesm', 'bright', 'net')

In [74]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [75]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}

In [76]:
data = pd.Series(data)

In [77]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [78]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [79]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [80]:
data_as_string_ext = data.astype('string')

In [81]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [82]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [83]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [85]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [86]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [87]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [88]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [89]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [90]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [91]:
values = pd.Series(["apple", "orange", "apple", "apple"] * 2)

In [92]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [93]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [94]:
pd.value_counts(values)

C:\Users\11321\AppData\Local\Temp\ipykernel_25044\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [95]:
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [96]:
values = pd.Series([0, 1, 0, 0] * 2)

In [97]:
dim = pd.Series(["apple", "orange"])

In [98]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [99]:
dim

0     apple
1    orange
dtype: object

In [101]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [103]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [104]:
N = len(fruits)

In [105]:
rng = np.random.default_rng(seed=12345)

In [107]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])

In [108]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [110]:
fruit_cat = df['fruit'].astype('category')

In [111]:
c = fruit_cat.array

In [112]:
type(c)

pandas.core.arrays.categorical.Categorical

In [113]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [115]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [117]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [118]:
df['fruit'] = df['fruit'].astype('category')

In [119]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [120]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [121]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [122]:
categories = ['foo', 'bar', 'baz']

In [123]:
codes = [0, 1, 2, 0, 0, 1]

In [124]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [125]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [126]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)

In [127]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [128]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [129]:
rng = np.random.default_rng(seed=12345)

In [130]:
draws = rng.standard_normal(1000)

In [131]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [132]:
bins = pd.qcut(draws, 4)

In [133]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [134]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [135]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [136]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [138]:
bins = pd.Series(bins, name='quartile')

In [141]:
results = (pd.Series(draws)
           .groupby(bins, observed=True)
           .agg(['count', 'min', 'max'])
           .reset_index())

In [142]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [143]:
N = 10_000_000

In [145]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [146]:
categories = labels.astype('category')

In [147]:
labels.memory_usage(deep=True)

520000132

In [151]:
import time

In [152]:
categories.memory_usage(deep=True)

10000512

In [155]:
%time _ = labels.astype('category')

CPU times: total: 250 ms
Wall time: 254 ms


In [156]:
%timeit labels.value_counts()

234 ms ± 19 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [157]:
%timeit categories.value_counts()

28.2 ms ± 1.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [158]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [159]:
cat_s = s.astype('category')

In [160]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [161]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [163]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [164]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [165]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [166]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [167]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [168]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [169]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [170]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [172]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [173]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True