In [1]:
import numpy as np


In [2]:
import pandas as pd

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [4]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [6]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [7]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [8]:
obj3


0      blue
2    purple
4    yellow
dtype: object

In [9]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [10]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])

In [11]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [12]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [13]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [14]:
states = ["Texas", "Utah", "California"]

In [15]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [16]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [17]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [19]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [20]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [21]:
new_obj = obj.drop("c")

In [22]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [23]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [30]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

In [31]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [33]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [36]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [38]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [39]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [40]:
obj["b"]

np.float64(1.0)

In [41]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [42]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [43]:
obj2

a    1
b    2
c    3
dtype: int64

In [44]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [54]:
obj1.iloc[[0, 2]]

2    1
1    3
dtype: int64

In [52]:
obj2.iloc[[0, 1]]

a    1
b    2
dtype: int64

In [55]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [57]:
obj2.loc["b":"c"]=5

In [59]:
obj2

a    1
b    5
c    5
dtype: int64

In [60]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New york"],
                    columns=["one", "two", "three", "four"])

In [61]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [62]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New york    13
Name: two, dtype: int64

In [64]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New york     14   12

In [65]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [66]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [67]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New york  False  False  False  False

In [68]:
data[data < 5] = 0

In [69]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [70]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [72]:
data.loc[["Colorado", "New york"]]

one  two  three  four
Colorado    0    5      6     7
New york   12   13     14    15

In [73]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [74]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [75]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [76]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [77]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [78]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [79]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [80]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [81]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New york   12   13     14

In [82]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [83]:
ser = pd.Series(np.arange(3.))

In [84]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [85]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [88]:
ser2[-1]

C:\Users\11321\AppData\Local\Temp\ipykernel_33764\811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [89]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [90]:
ser.iloc[-1]

np.float64(2.0)

In [91]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [92]:
data.loc[:, "one"] = 1

In [93]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New york    1   13     14    15

In [96]:
data.iloc[2] = 5

In [97]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New york    1   13     14    15
one         2    2      2     2

In [101]:
data = data.drop(index=["one"])

In [102]:
data.loc[data["four"] > 5] = 3

In [103]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New york    3    3      3     3

In [104]:
data.loc[data.three == 5]["three"] = 6

C:\Users\11321\AppData\Local\Temp\ipykernel_33764\867481848.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 5]["three"] = 6


In [105]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New york    3    3      3     3

In [106]:
data.loc[data.three == 5, "three"] = 6

In [107]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New york    3    3      3     3

In [108]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5] ,index=["a", "c", "d", "e"])

In [109]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [112]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [113]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

In [116]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

In [117]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [118]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [119]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [120]:
df1 = pd.DataFrame({"A": [2, 2]})

In [121]:
df2 = pd.DataFrame({"B": [3, 4]})

In [122]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [123]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))

In [124]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

In [125]:
df2.loc[1, "b"] = np.nan

In [126]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [127]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [128]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [129]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [130]:
df1.add(df2)

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [131]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [132]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [133]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [134]:
arr = np.arange(12.).reshape((3, 4))

In [135]:
arr[0]

array([0., 1., 2., 3.])

In [136]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [137]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])